/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jailproject;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author root
 */
public class mainscreen1 extends javax.swing.JFrame {

    /**
     * Creates new form mainscreen1 which the main page containing all the options of the jailor like modifying prisoner details,warden details,check visitors of the prisoner,check vacancy in the prison
     */
    public mainscreen1() {
        initComponents();
    }
    
    public void close(){
        
        WindowEvent winclosingEvent= new WindowEvent(this,WindowEvent.WINDOW_CLOSING); 
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winclosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnmodpri = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnmodwrn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnsrcpri = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnsrcwrn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnchkcst = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        btnchkvan = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cantarell", 3, 18)); // NOI18N
        jLabel1.setText("PRISON MANAGEMENT SYSTEM");

        jLabel2.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabel2.setText("MODIFY PRISONERS DETAIL");

        btnmodpri.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        btnmodpri.setText("Modify Prisoner");
        btnmodpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodpriActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabel3.setText("MODIFY WARDEN DETAIL");

        btnmodwrn.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        btnmodwrn.setText("Modify Warden");
        btnmodwrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodwrnActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabel4.setText("SEARCH PRISONER");

        btnsrcpri.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        btnsrcpri.setText("Search Prisoner");
        btnsrcpri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrcpriActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabel5.setText("SEARCH WARDEN");

        btnsrcwrn.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        btnsrcwrn.setText("Search Warden");
        btnsrcwrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsrcwrnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabel6.setText("CHECK VISITOR OF PRISONER");

        btnchkcst.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        btnchkcst.setText("Chk Visitor");
        btnchkcst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchkcstActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        jLabel7.setText("CHECK VACANCY IN PRISON");

        btnchkvan.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        btnchkvan.setText("Chk Vacancy");
        btnchkvan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchkvanActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Cantarell", 3, 15)); // NOI18N
        btnexit.setText("EXIT");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnmodpri, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnmodwrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsrcpri, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                        .addComponent(btnsrcwrn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnchkcst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnchkvan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodpri))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmodwrn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsrcpri))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsrcwrn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchkcst))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchkvan))
                .addGap(18, 18, 18)
                .addComponent(btnexit, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnchkcstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchkcstActionPerformed
        close();
        checkvisitor cv=new checkvisitor();
       cv.setVisible(true);
    }//GEN-LAST:event_btnchkcstActionPerformed

    private void btnmodpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodpriActionPerformed
        close();
        modifyprisoner mp=new modifyprisoner();
        mp.setVisible(true);
    }//GEN-LAST:event_btnmodpriActionPerformed

    private void btnmodwrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodwrnActionPerformed
        close();
        modifywarden mw=new modifywarden();
        mw.setVisible(true);
    }//GEN-LAST:event_btnmodwrnActionPerformed

    private void btnsrcwrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrcwrnActionPerformed
        close();
        searchwarden sw = new searchwarden();
        sw.setVisible(true);
    }//GEN-LAST:event_btnsrcwrnActionPerformed

    private void btnsrcpriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsrcpriActionPerformed
        close();
        searchprisoner sp = new searchprisoner();
        sp.setVisible(true);
    }//GEN-LAST:event_btnsrcpriActionPerformed

    private void btnchkvanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchkvanActionPerformed
        close();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=(Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/minorproject","root","mysql");
            
            Statement stmt=null;
            ResultSet rs=null;
            
            stmt=con.createStatement();
            String sql = "Select * from prisoner";
            rs=stmt.executeQuery(sql);
            int numberofshells=100;
            int numberofoccupiedshell=0;
            int numberofunoccupiedshells;
            while(rs.next())
            {
                numberofoccupiedshell++;
            }
            
            numberofunoccupiedshells = numberofshells-numberofoccupiedshell;
            int percentageempty=(numberofunoccupiedshells*100)/numberofshells;
            JOptionPane.showMessageDialog(this,"Total number of shells = "+(numberofshells)+" \nNumber of vacant shells = "+( numberofunoccupiedshells)+" \n Percentage of shells vacant = "+(percentageempty)+"%");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(mainscreen1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnchkvanActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        close();
        firstpage fp = new firstpage();
        fp.setVisible(true);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainscreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainscreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainscreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainscreen1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainscreen1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchkcst;
    private javax.swing.JButton btnchkvan;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnmodpri;
    private javax.swing.JButton btnmodwrn;
    private javax.swing.JButton btnsrcpri;
    private javax.swing.JButton btnsrcwrn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
